// Generated by scripts/find-uploads.mjs. Edit scripts/films.json and re-run
// the script rather than editing this file by hand. IDs from earlier runs are
// kept; delete one here if check.html reports it dead and it isn't coming back.
export const FOUND = [
  {
    "imdb": "tt0111161",
    "title": "The Shawshank Redemption",
    "year": 1994,
    "runtime": 142,
    "genres": [
      "Drama"
    ],
    "aliases": [],
    "youtube": [
      "1xm2NuHTDug"
    ],
    "skipStart": 3,
    "skipEnd": 10,
    "zoom": 1.25
  },
  {
    "imdb": "tt0068646",
    "title": "The Godfather",
    "year": 1972,
    "runtime": 175,
    "genres": [
      "Crime",
      "Drama"
    ],
    "aliases": [],
    "youtube": [
      "8Khh5G0DMow"
    ],
    "skipStart": 3,
    "skipEnd": 4,
    "zoom": 1.25
  },
  {
    "imdb": "tt0468569",
    "title": "The Dark Knight",
    "year": 2008,
    "runtime": 152,
    "genres": [
      "Action",
      "Crime",
      "Drama"
    ],
    "aliases": [],
    "youtube": [
      "NM7Um5lensU"
    ],
    "skipStart": 3,
    "skipEnd": 10,
    "zoom": 1.25
  },
  {
    "imdb": "tt0071562",
    "title": "The Godfather Part II",
    "year": 1974,
    "runtime": 202,
    "genres": [
      "Crime",
      "Drama"
    ],
    "aliases": [
      "The Godfather 2",
      "Godfather Part 2"
    ],
    "youtube": [
      "W4P2MVO9_Vc"
    ],
    "skipStart": 3,
    "skipEnd": 4,
    "zoom": 1.25
  },
  {
    "imdb": "tt0050083",
    "title": "12 Angry Men",
    "year": 1957,
    "runtime": 96,
    "genres": [
      "Crime",
      "Drama"
    ],
    "aliases": [
      "Twelve Angry Men"
    ],
    "youtube": [
      "QNDmvX-WPY4"
    ],
    "skipStart": 3,
    "skipEnd": 4,
    "zoom": 1.25
  },
  {
    "imdb": "tt0108052",
    "title": "Schindler's List",
    "year": 1993,
    "runtime": 195,
    "genres": [
      "Biography",
      "Drama",
      "History"
    ],
    "aliases": [],
    "youtube": [
      "wgQGoZr_o2s"
    ],
    "skipStart": 3,
    "skipEnd": 10,
    "zoom": 1.25
  },
  {
    "imdb": "tt0060196",
    "title": "The Good, the Bad and the Ugly",
    "year": 1966,
    "runtime": 178,
    "genres": [
      "Adventure",
      "Western"
    ],
    "aliases": [
      "Il buono, il brutto, il cattivo",
      "The Good the Bad and the Ugly"
    ],
    "youtube": [
      "IFaNlr6qGQ0"
    ],
    "skipStart": 3,
    "skipEnd": 4,
    "zoom": 1.25
  }
];
